version: 1
send_anonymous_usage_stats: true
project_id: "tap-jira"
default_environment: dev
plugins:
  extractors:
  - name: "tap-jira"
    namespace: "tap_jira"
    pip_url: -e .
    capabilities:
    - state
    - catalog
    - discover
    - about
    - stream-maps
    settings:
    - name: username
    - name: password
      kind: password
    - name: start_date
    - name: end_date
    - name: access_token  
    - name: auth_type
    - name: account_id
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
  - name: target-csv
    variant: hotgluexyz
    pip_url: git+https://github.com/hotgluexyz/target-csv.git@0.3.3
    config:
      destination_path: $MELTANO_PROJECT_ROOT/output
  - name: target-snowflake
    variant: transferwise
    pip_url: pipelinewise-target-snowflake
    config:
      batch_size: 5
environments:
- name: dev
- name: staging
- name: prod
