version: 1
send_anonymous_usage_stats: true
project_id: "tap-jira"
default_environment: dev
plugins:
  extractors:
  - name: "tap-jira"
    namespace: "tap_jira"
    pip_url: -e .
    capabilities:
    - state
    - catalog
    - discover
    - about
    - stream-maps
    settings:
    - name: username
      value: ${TAP_JIRA_USERNAME}
    - name: password
      value: ${TAP_JIRA_PASSWORD}
      kind: password
    - name: start_date
      value: '2010-01-01T00:00:00Z'
    - name: end_date
      value: '2023-05-020T00:00:00Z'
    - name: board_id
      value: ${TAP_JIRA_BOARD_ID} 
    - name: account_id 
      value:  ${TAP_JIRA_ACCOUNT_ID}
    - name: project_id 
      value: ${TAP_JIRA_PROJECT_ID}
    - name: role_admin_id 
      value: ${TAP_JIRA_ROLE_ADMIN_ID}
    - name: role_viewer_id 
      value: ${TAP_JIRA_ROLE_VIEWER_ID}
    - name: role_member_id 
      value: ${TAP_JIRA_ROLE_MEMBER_ID}
    - name: role_altasian_id 
      value: ${TAP_JIRA_ROLE_ALTASIAN_ID}      
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
  - name: target-csv
    variant: hotgluexyz
    pip_url: git+https://github.com/hotgluexyz/target-csv.git@0.3.3
    config:
      destination_path: $MELTANO_PROJECT_ROOT/output
  - name: target-snowflake
    variant: transferwise
    pip_url: pipelinewise-target-snowflake
    config:
      batch_size: 5
environments:
- name: dev
  config:
    plugins:
      loaders:
      - name: target-csv
      - name: target-snowflake
        config:
          primary_key_required: false
          add_metadata_columns: true
- name: staging
- name: prod
