### A CI workflow template that runs linting and python testing
### TODO: Modify as needed or as desired.

name: Test tap-jira

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Only lint using the primary version used for dev
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pipx and Poetry
      run: |
        pip install pipx poetry
    - name: Run lint command from tox.ini
      run: |
        pipx run tox -e lint

  pytest:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        pip install poetry
    - name: Install dependencies
      run: |
        poetry install
    - name: Test with pytest
      id: test_pytest
      continue-on-error: false
      env:
         TAP_JIRA_USERNAME: ${{ secrets.username }}
         TAP_JIRA_PASSWORD: ${{ secrets.password }}
         TAP_JIRA_ACCOUNT_ID: ${{ secrets.account_id }}
         TAP_JIRA_BOARD_ID: ${{ secrets.board_id }}
         TAP_JIRA_PROJECT_ID: ${{ secrets.project_id }}
         TAP_JIRA_ROLE_ADMIN_ID: ${{ secrets.role_admin_id }}
         TAP_JIRA_ROLE_VIEWER_ID: ${{ secrets.role_viewer_id }}
         TAP_JIRA_ROLE_MEMBER_ID: ${{ secrets.role_member_id }}
         TAP_JIRA_ROLE_ALTASIAN_ID: ${{ secrets.role_altasian_id }}
      run: |
        poetry run pytest --capture=no
